### PR TITLE
Change key to diningItems

### PR DESCRIPTION
**Pull request by ilikesymmetry**

### CODE REVIEW

**Review by young-k — COMMENTED** [review]
Does this fix the `Trillium` problem? Won't there be two Trilliums?

**Comment by ilikesymmetry** [comment]
this just allows me to use the parse_dining_items method already made in data.py

**Comment by ilikesymmetry** [comment]
there won't be two trilliums, don't worry

**Review by young-k — APPROVED** [review]
LGTM

**Pull request merged**
